repos:
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.2
    hooks:
    - id: flake8
      args: ["--config=setup.cfg"]
      language_version: python3
      additional_dependencies: [
        flake8-2020, # flake8 plugin which checks for misuse of `sys.version` or `sys.version_info`
        flake8-blind-except, # A flake8 extension that checks for blind except: statements
        flake8-bugbear, # A plugin for flake8 finding likely bugs and design problems in your program.
        #                 # Contains warnings that don't belong in pyflakes and pycodestyle.
        flake8-builtins, # Check for python builtins being used as variables or parameters.
        flake8-comprehensions, # It helps you write a better list/set/dict comprehensions.
        flake8-copyright, # Adds copyright checks to flake8
        flake8-deprecated, # Warns about deprecated method calls.
        dlint, # Dlint is a tool for encouraging best coding practices and helping ensure we're writing secure Python code.
        # flake8-docstrings, # Extension for flake8 which uses pydocstyle to check docstrings
        flake8-eradicate, # Flake8 plugin to find commented out code
        flake8-license,
        # pandas-vet, # A Flake8 plugin that provides opinionated linting for pandas code
        flake8-pytest, # pytest assert checker plugin for flake8
        flake8-variables-names, # flake8 extension that helps to make more readable variables names
        pep8-naming, # Check PEP-8 naming conventions, plugin for flake8
      ]
